# Generated by Django 3.2 on 2021-04-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='user_id',
        ),
    ]
