# Generated by Django 3.2 on 2021-04-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_no', models.CharField(max_length=15)),
                ('loan_amount', models.FloatField(default=0.0)),
                ('payable_amount', models.FloatField(default=0.0)),
                ('loan_approval', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('date', models.DateField(default='0000-00-00')),
            ],
            options={
                'db_table': 'Loan_Application',
            },
        ),
    ]
