# Generated by Django 3.2 on 2021-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalments',
            name='payment_date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
