# Generated by Django 3.2 on 2021-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_seeker', '0002_alter_instalments_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanseeker',
            name='dob',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='loanseekerswallet',
            name='deadline',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
