# Generated by Django 3.2 on 2021-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_seeker', '0003_auto_20210413_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalments',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loanseeker',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loanseekerswallet',
            name='deadline',
            field=models.DateField(),
        ),
    ]
