# Generated by Django 3.2 on 2021-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_seeker', '0004_auto_20210413_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanseekerswallet',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
